spring:
  datasource:
    password: cervejaria
    username: cervejaria
    url: jdbc:mysql://localhost:3306/cervejaria
  jpa:
    hibernate:
      ddl-auto: update
eureka-context: localhost
auth-context: localhost
