
spring:  application:    name: 'loja'

eureka:  client:    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone: http://${eureka-context}:8761/eureka
      
security:
  oauth2:
    resource:
      user-info-uri: http://${auth-context}:8088/user
      
hystrix:
  shareSecurityContext: true