
server:
  port: 8888
  
  
spring:
  profiles:
    active: uri
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fernandodpcarvalho/microservices-spring-app/
          search-paths: config-repo
